/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#3b674f",
        "on-primary-fixed": "#002112",
        "surface-container-lowest": "#051109",
        "secondary-container": "#00a572",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#86b598",
        "error-container": "#93000a",
        "surface": "#09160e",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00311f",
        "surface-container-highest": "#2a382f",
        "on-primary-fixed-variant": "#234f38",
        "surface-dim": "#09160e",
        "on-tertiary-fixed": "#2a1700",
        "on-primary": "#073823",
        "surface-container": "#15221a",
        "on-secondary-fixed-variant": "#005236",
        "error": "#ffb4ab",
        "inverse-on-surface": "#26332a",
        "surface-variant": "#2a382f",
        "background": "#09160e",
        "tertiary-fixed-dim": "#ffb95f",
        "primary-container": "#1a4731",
        "primary-fixed": "#bdeecf",
        "surface-container-low": "#111e16",
        "outline-variant": "#414943",
        "secondary": "#4edea3",
        "on-surface-variant": "#c1c9c1",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#2f3c33",
        "tertiary-container": "#5a3700",
        "on-surface": "#d7e7d9",
        "on-secondary": "#003824",
        "outline": "#8b938c",
        "inverse-surface": "#d7e7d9",
        "tertiary": "#ffb95f",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed-variant": "#653e00",
        "primary": "#a1d1b4",
        "primary-fixed-dim": "#a1d1b4",
        "on-tertiary-container": "#ec9700",
        "surface-container-high": "#202d24",
        "on-error": "#690005",
        "secondary-fixed-dim": "#4edea3",
        "surface-tint": "#a1d1b4",
        "on-tertiary": "#472a00",
        "on-background": "#d7e7d9"
      },
      fontFamily: {
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Be Vietnam Pro', 'sans-serif'],
      },
      borderRadius: {
        'sm': '0.5rem',
        DEFAULT: '1rem',
        'md': '1.5rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '24px',
        'lg': '40px',
        'xl': '64px',
        'gutter': '16px',
        'margin-mobile': '20px',
        'margin-desktop': '120px',
      },
      boxShadow: {
        'card': '0 8px 32px rgba(45, 90, 39, 0.08)',
        'modal': '0 16px 48px rgba(45, 90, 39, 0.12)',
      },
      keyframes: {
        'pop-up': {
          '0%': { opacity: '0', transform: 'scale(0.85) translateY(10px)' },
          '60%': { opacity: '1', transform: 'scale(1.03) translateY(-2px)' },
          '100%': { transform: 'scale(1) translateY(0)' },
        },
        'pop-down': {
          '0%': { opacity: '1', transform: 'scale(1) translateY(0)' },
          '40%': { opacity: '0.8', transform: 'scale(1.02) translateY(-2px)' },
          '100%': { opacity: '0', transform: 'scale(0.85) translateY(10px)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-down': {
          '0%': { opacity: '0', transform: 'translateY(-30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-left': {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-right': {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-in': {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1', transform: 'scale(1.08)' },
          '70%': { transform: 'scale(0.96)' },
          '100%': { transform: 'scale(1)' },
        },
        'bounce-soft': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'shake': {
          '0%, 100%': { transform: 'translateX(0)' },
          '15%': { transform: 'translateX(-4px)' },
          '30%': { transform: 'translateX(4px)' },
          '45%': { transform: 'translateX(-3px)' },
          '60%': { transform: 'translateX(3px)' },
          '75%': { transform: 'translateX(-1px)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(21, 66, 18, 0.2)' },
          '50%': { boxShadow: '0 0 20px 6px rgba(21, 66, 18, 0.15)' },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'rotate-in': {
          '0%': { opacity: '0', transform: 'rotate(-12deg) scale(0.9)' },
          '100%': { opacity: '1', transform: 'rotate(0) scale(1)' },
        },
        'flip-in': {
          '0%': { opacity: '0', transform: 'perspective(400px) rotateX(-20deg)' },
          '100%': { opacity: '1', transform: 'perspective(400px) rotateX(0)' },
        },
      },
      animation: {
        'pop-up': 'pop-up 0.45s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'pop-down': 'pop-down 0.35s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'slide-up': 'slide-up 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-down': 'slide-down 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-left': 'slide-left 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-right': 'slide-right 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-in': 'fade-in 0.4s ease-out both',
        'fade-out': 'fade-out 0.3s ease-in both',
        'scale-in': 'scale-in 0.35s cubic-bezier(0.16, 1, 0.3, 1) both',
        'bounce-in': 'bounce-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) both',
        'bounce-soft': 'bounce-soft 2s ease-in-out infinite',
        'shake': 'shake 0.5s ease-in-out',
        'float': 'float 3s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'rotate-in': 'rotate-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'flip-in': 'flip-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
    },
  },
  plugins: [],
}
