import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  English: {
    "Dashboard": "Dashboard",
    "Crop Insights": "Crop Insights",
    "Pest Risk": "Pest Risk",
    "Generate Summary": "Generate Summary",
    "Alerts": "Alerts",
    "Home": "Home",
    "AI": "AI",
    "Forecast": "Forecast",
    "Settings": "Settings",
    "Welcome back": "Welcome back",
    "Here is your active field intelligence for today.": "Here is your active field intelligence for today.",
    "Change Analysis Location": "Change Analysis Location",
    "Search any place in India...": "Search any place in India...",
    "Doctor": "Doctor",
    "India": "India",
    "Community": "Community",
    "Login with Mobile (OTP)": "Login with Mobile (OTP)",
    "Login with Gmail": "Login with Gmail",
    "Continue as Guest": "Continue as Guest",
    "Live Weather": "Live Weather",
    "Overall Health": "Overall Health",
    "Data & Forecast": "Data & Forecast",
    "Pest Warning": "Pest Warning",
    "Manage your preferences": "Manage your preferences",
    "Language": "Language",
    "Update Location": "Update Location",
    "Save Settings": "Save Settings",
    "Logout": "Logout",
    "AI-powered farming recommendations": "AI-powered farming recommendations",
    "Daily Advisory": "Daily Advisory",
    "Summary": "Summary",
    "Recommended Action": "Recommended Action",
    "Analyzing latest field conditions...": "Analyzing latest field conditions...",
    "Please wait": "Please wait",
    "Severe heat and water stress detected.": "Severe heat and water stress detected.",
    "Irrigate immediately.": "Irrigate immediately.",
    "High humidity creating favorable conditions for fungal/pest attacks.": "High humidity creating favorable conditions for fungal/pest attacks.",
    "Apply preventive neem spray.": "Apply preventive neem spray.",
    "Current environmental conditions are optimal.": "Current environmental conditions are optimal.",
    "Logout": "Logout",
    "AI-powered farming recommendations": "AI-powered farming recommendations",
    "Daily Advisory": "Daily Advisory",
    "Summary": "Summary",
    "Recommended Action": "Recommended Action",
    "Analyzing latest field conditions...": "Analyzing latest field conditions...",
    "Please wait": "Please wait",
    "Severe heat and water stress detected.": "Severe heat and water stress detected.",
    "Irrigate immediately.": "Irrigate immediately.",
    "High humidity creating favorable conditions for fungal/pest attacks.": "High humidity creating favorable conditions for fungal/pest attacks.",
    "Apply preventive neem spray.": "Apply preventive neem spray.",
    "Current environmental conditions are optimal.": "Current environmental conditions are optimal.",
    "Maintain regular farming schedule.": "Maintain regular farming schedule.",
    "Good Morning": "Good Morning",
    "Good Afternoon": "Good Afternoon",
    "Good Evening": "Good Evening",
    "Live Weather": "Live Weather",
    "Pest Risk": "Pest Risk",
    "Overall Health": "Overall Health",
    "Based on weather model": "Based on weather model",
    "Forecast feature disabled while using backend API logic": "Forecast feature disabled while using backend API logic",
    "Forecast disabled": "Forecast disabled",
    "Forecast disabled": "Forecast disabled",
    "The 7-day forecast model is disabled while running via the backend API logic.": "The 7-day forecast model is disabled while running via the backend API logic.",
    "Stage": "Stage",
    "7-Day Forecast": "7-Day Forecast",
    "Loading forecast...": "Loading forecast...",
    "No forecast available": "No forecast available",
    "Day": "Day",
    "Temp": "Temp",
    "Rain": "Rain",
    "Wind": "Wind",
    "Pest risk and weather trends for": "Pest risk and weather trends for",
    "Current Risk Factors": "Current Risk Factors"
  },
  Tamil: {
    "Dashboard": "முகப்பு (Dashboard)",
    "Crop Insights": "பயிர் நுண்ணறிவு",
    "Pest Risk": "பூச்சி ஆபத்து",
    "Generate Summary": "சுருக்கத்தை உருவாக்கு",
    "Alerts": "எச்சரிக்கைகள்",
    "Home": "முகப்பு",
    "AI": "AI",
    "Forecast": "முன்னறிவிப்பு",
    "Settings": "அமைப்புகள்",
    "Welcome back": "மீண்டும் வருக",
    "Here is your active field intelligence for today.": "இன்றைய உங்கள் கள நுண்ணறிவு இதோ.",
    "Change Analysis Location": "பகுப்பாய்வு இருப்பிடத்தை மாற்றவும்",
    "Search any place in India...": "இந்தியாவில் எந்த இடத்தையும் தேடுங்கள்...",
    "Doctor": "மருத்துவர்",
    "India": "இந்தியா",
    "Community": "சமூகம்",
    "Login with Mobile (OTP)": "மொபைல் மூலம் உள்நுழையவும்",
    "Login with Gmail": "ஜிமெயில் மூலம் உள்நுழையவும்",
    "Continue as Guest": "விருந்தினராக தொடரவும்",
    "Live Weather": "தற்போதைய வானிலை",
    "Overall Health": "ஒட்டுமொத்த ஆரோக்கியம்",
    "Data & Forecast": "தரவு & முன்னறிவிப்பு",
    "Pest Warning": "பூச்சி எச்சரிக்கை",
    "Manage your preferences": "உங்கள் விருப்பங்களை நிர்வகிக்கவும்",
    "Language": "மொழி",
    "Update Location": "இருப்பிடத்தை புதுப்பிக்கவும்",
    "Save Settings": "அமைப்புகளை சேமிக்க",
    "Logout": "வெளியேறு",
    "AI Plant Doctor": "AI தாவர மருத்துவர்",
    "Upload a photo of your plant for an instant diagnosis powered by Gemini Vision API.": "ஜெமினி விஷன் ஏபிஐ மூலம் உடனடி நோயறிதலுக்கு உங்கள் தாவரத்தின் புகைப்படத்தைப் பதிவேற்றவும்.",
    "Click or drop to change image": "படத்தை மாற்ற கிளிக் செய்யவும் அல்லது விடவும்",
    "Drag and drop an image here": "படத்தை இங்கே இழுத்து விடவும்",
    "or click to browse from your computer": "அல்லது உங்கள் கணினியிலிருந்து உலாவுவதற்கு கிளிக் செய்யவும்",
    "Analyze Plant Image": "தாவரப் படத்தைப் பகுப்பாய்வு செய்",
    "Diagnostic Report": "கண்டறியும் அறிக்கை",
    "Generated by Gemini 3.5-flash": "ஜெமினி 3.5-ஃப்ளாஷ் மூலம் உருவாக்கப்பட்டது",
    "Recent Diagnoses": "சமீபத்திய நோயறிதல்கள்",
    "No recent diagnoses found.": "சமீபத்திய நோயறிதல்கள் எதுவும் காணப்படவில்லை.",
    "Unknown error from API": "API இலிருந்து அறியப்படாத பிழை",
    "Cannot reach the backend server.": "பின்தள சேவையகத்தை அணுக முடியவில்லை.",
    "Farmer Community": "விவசாயிகள் சமூகம்",
    "Share tips, ask questions, help each other grow": "குறிப்புகளைப் பகிரவும், கேள்விகளைக் கேட்கவும், ஒருவருக்கொருவர் வளர உதவவும்",
    "Trending in Your Region": "உங்கள் பிராந்தியத்தில் ட்ரெண்டிங்",
    "Share your farming experience...": "உங்கள் விவசாய அனுபவத்தைப் பகிரவும்...",
    "No posts in this category yet.": "இந்த பிரிவில் இன்னும் பதிவுகள் இல்லை.",
    "Be the first to share!": "பகிர்வதில் முதல் ஆளாக இருங்கள்!",
    "Helpful": "பயனுள்ளது",
    "Replies": "பதில்கள்",
    "Write a reply...": "பதிலளிக்க...",
    "Send": "அனுப்பு",
    "Smart Farming, Simple Guidance": "ஸ்மார்ட் விவசாயம், எளிய வழிகாட்டுதல்",
    "Get Started": "தொடங்குங்கள்",
    "Tell us about yourself": "உங்களைப் பற்றி சொல்லுங்கள்",
    "Farmer Name": "விவசாயி பெயர்",
    "Enter your name": "உங்கள் பெயரை உள்ளிடவும்",
    "Location / Village": "இடம் / கிராமம்",
    "E.g., Coimbatore": "எ.கா., கோயம்புத்தூர்",
    "State": "மாநிலம்",
    "Farm Size (Acres)": "பண்ணை அளவு (ஏக்கர்)",
    "E.g., 5": "எ.கா., 5",
    "Next": "அடுத்து",
    "Crop Details": "பயிர் விவரங்கள்",
    "Which crop are you growing?": "நீங்கள் என்ன பயிர் வளர்க்கிறீர்கள்?",
    "Growth Stage": "வளர்ச்சி நிலை",
    "Expected Yield Target (kg/acre)": "எதிர்பார்க்கப்படும் மகசூல் இலக்கு (கிலோ/ஏக்கர்)",
    "E.g., 2000": "எ.கா., 2000",
    "When did you sow?": "நீங்கள் எப்போது விதைத்தீர்கள்?",
    "Back": "பின் செல்ல",
    "Finish Setup": "அமைப்பை முடிக்கவும்",
    "AI-powered farming recommendations": "AI-இயக்கப்படும் விவசாய பரிந்துரைகள்",
    "Daily Advisory": "தினசரி ஆலோசனை",
    "Summary": "சுருக்கம்",
    "Recommended Action": "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    "Analyzing latest field conditions...": "சமீபத்திய கள நிலைகளை பகுப்பாய்வு செய்கிறது...",
    "Please wait": "காத்திருக்கவும்",
    "Severe heat and water stress detected.": "கடுமையான வெப்பம் மற்றும் நீர் அழுத்தம் கண்டறியப்பட்டது.",
    "Irrigate immediately.": "உடனடியாக நீர்ப்பாசனம் செய்யவும்.",
    "High humidity creating favorable conditions for fungal/pest attacks.": "அதிக ஈரப்பதம் பூஞ்சை/பூச்சி தாக்குதல்களுக்கு சாதகமான நிலைமைகளை உருவாக்குகிறது.",
    "Apply preventive neem spray.": "தடுப்பு வேப்ப எண்ணெய் தெளிக்கவும்.",
    "Current environmental conditions are optimal.": "தற்போதைய சுற்றுச்சூழல் நிலைமைகள் உகந்தவை.",
    "Logout": "வெளியேறு",
    "AI-powered farming recommendations": "AI-இயக்கப்படும் விவசாய பரிந்துரைகள்",
    "Daily Advisory": "தினசரி ஆலோசனை",
    "Summary": "சுருக்கம்",
    "Recommended Action": "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    "Analyzing latest field conditions...": "சமீபத்திய கள நிலைகளை பகுப்பாய்வு செய்கிறது...",
    "Please wait": "காத்திருக்கவும்",
    "Severe heat and water stress detected.": "கடுமையான வெப்பம் மற்றும் நீர் அழுத்தம் கண்டறியப்பட்டது.",
    "Irrigate immediately.": "உடனடியாக நீர்ப்பாசனம் செய்யவும்.",
    "High humidity creating favorable conditions for fungal/pest attacks.": "அதிக ஈரப்பதம் பூஞ்சை/பூச்சி தாக்குதல்களுக்கு சாதகமான நிலைமைகளை உருவாக்குகிறது.",
    "Apply preventive neem spray.": "தடுப்பு வேப்ப எண்ணெய் தெளிக்கவும்.",
    "Current environmental conditions are optimal.": "தற்போதைய சுற்றுச்சூழல் நிலைமைகள் உகந்தவை.",
    "Maintain regular farming schedule.": "வழக்கமான விவசாய அட்டவணையை பராமரிக்கவும்.",
    "Good Morning": "காலை வணக்கம்",
    "Good Afternoon": "மதிய வணக்கம்",
    "Good Evening": "மாலை வணக்கம்",
    "Live Weather": "நேரலை வானிலை",
    "Pest Risk": "பூச்சி ஆபத்து",
    "Overall Health": "ஒட்டுமொத்த ஆரோக்கியம்",
    "Based on weather model": "வானிலை மாதிரியை அடிப்படையாகக் கொண்டது",
    "Forecast feature disabled while using backend API logic": "பின்தள API லாஜிக்கைப் பயன்படுத்தும் போது முன்னறிவிப்பு முடக்கப்பட்டுள்ளது",
    "Forecast disabled": "முன்னறிவிப்பு முடக்கப்பட்டுள்ளது",
    "Forecast disabled": "முன்னறிவிப்பு முடக்கப்பட்டுள்ளது",
    "The 7-day forecast model is disabled while running via the backend API logic.": "பின்தள API லாஜிக்கைப் பயன்படுத்தும் போது 7 நாள் முன்னறிவிப்பு முடக்கப்பட்டுள்ளது.",
    "Stage": "பருவம்",
    "7-Day Forecast": "7 நாள் முன்னறிவிப்பு",
    "Loading forecast...": "முன்னறிவிப்பு ஏற்றப்படுகிறது...",
    "No forecast available": "முன்னறிவிப்பு கிடைக்கவில்லை",
    "Day": "நாள்",
    "Temp": "வெப்பம்",
    "Rain": "மழை",
    "Wind": "காற்று",
    "Pest risk and weather trends for": "பூச்சி ஆபத்து மற்றும் வானிலை போக்குகள்",
    "Current Risk Factors": "தற்போதைய ஆபத்து காரணிகள்"
  },
  Hindi: {
    "Dashboard": "डैशबोर्ड",
    "Crop Insights": "फसल की जानकारी",
    "Pest Risk": "कीट जोखिम",
    "Generate Summary": "सारांश बनाएं",
    "Alerts": "अलर्ट",
    "Home": "होम",
    "AI": "एआई (AI)",
    "Forecast": "पूर्वानुमान",
    "Settings": "सेटिंग्स",
    "Welcome back": "वापसी पर स्वागत है",
    "Here is your active field intelligence for today.": "यहां आज के लिए आपकी सक्रिय क्षेत्र खुफिया जानकारी है।",
    "Change Analysis Location": "विश्लेषण स्थान बदलें",
    "Search any place in India...": "भारत में कोई भी जगह खोजें...",
    "Doctor": "डॉक्टर",
    "India": "भारत",
    "Community": "समुदाय",
    "Login with Mobile (OTP)": "मोबाइल से लॉगिन करें",
    "Login with Gmail": "जीमेल से लॉगिन करें",
    "Continue as Guest": "अतिथि के रूप में जारी रखें",
    "Live Weather": "लाइव मौसम",
    "Overall Health": "समग्र स्वास्थ्य",
    "Data & Forecast": "डेटा और पूर्वानुमान",
    "Pest Warning": "कीट चेतावनी",
    "Manage your preferences": "अपनी प्राथमिकताएं प्रबंधित करें",
    "Language": "भाषा",
    "Update Location": "स्थान अपडेट करें",
    "Save Settings": "सेटिंग्स सहेजें",
    "Logout": "लॉग आउट",
    "AI-powered farming recommendations": "एआई-संचालित कृषि सिफारिशें",
    "Daily Advisory": "दैनिक सलाह",
    "Summary": "सारांश",
    "Recommended Action": "अनुशंसित कार्रवाई",
    "Analyzing latest field conditions...": "नवीनतम क्षेत्र की स्थितियों का विश्लेषण...",
    "Please wait": "कृपया प्रतीक्षा करें",
    "Severe heat and water stress detected.": "गंभीर गर्मी और पानी के तनाव का पता चला है।",
    "Irrigate immediately.": "तुरंत सिंचाई करें।",
    "High humidity creating favorable conditions for fungal/pest attacks.": "उच्च आर्द्रता फंगल/कीट हमलों के लिए अनुकूल परिस्थितियां बना रही है।",
    "Apply preventive neem spray.": "निवारक नीम स्प्रे लागू करें।",
    "Current environmental conditions are optimal.": "वर्तमान पर्यावरणीय स्थितियां इष्टतम हैं।",
    "Logout": "लॉग आउट",
    "AI-powered farming recommendations": "एआई-संचालित कृषि सिफारिशें",
    "Daily Advisory": "दैनिक सलाह",
    "Summary": "सारांश",
    "Recommended Action": "अनुशंसित कार्रवाई",
    "Analyzing latest field conditions...": "नवीनतम क्षेत्र की स्थितियों का विश्लेषण...",
    "Please wait": "कृपया प्रतीक्षा करें",
    "Severe heat and water stress detected.": "गंभीर गर्मी और पानी के तनाव का पता चला है।",
    "Irrigate immediately.": "तुरंत सिंचाई करें।",
    "High humidity creating favorable conditions for fungal/pest attacks.": "उच्च आर्द्रता फंगल/कीट हमलों के लिए अनुकूल परिस्थितियां बना रही है।",
    "Apply preventive neem spray.": "निवारक नीम स्प्रे लागू करें।",
    "Current environmental conditions are optimal.": "वर्तमान पर्यावरणीय स्थितियां इष्टतम हैं।",
    "Maintain regular farming schedule.": "नियमित खेती का कार्यक्रम बनाए रखें।",
    "Good Morning": "सुप्रभात",
    "Good Afternoon": "शुभ दोपहर",
    "Good Evening": "शुभ संध्या",
    "Live Weather": "लाइव मौसम",
    "Pest Risk": "कीट जोखिम",
    "Overall Health": "समग्र स्वास्थ्य",
    "Based on weather model": "मौसम मॉडल पर आधारित",
    "Forecast feature disabled while using backend API logic": "बैकएंड एपीआई लॉजिक का उपयोग करते समय पूर्वानुमान अक्षम है",
    "Forecast disabled": "पूर्वानुमान अक्षम है",
    "Forecast disabled": "पूर्वानुमान अक्षम है",
    "The 7-day forecast model is disabled while running via the backend API logic.": "बैकएंड एपीआई लॉजिक का उपयोग करते समय 7-दिवसीय पूर्वानुमान मॉडल अक्षम है।",
    "Stage": "चरण",
    "7-Day Forecast": "7-दिवसीय पूर्वानुमान",
    "Loading forecast...": "पूर्वानुमान लोड हो रहा है...",
    "No forecast available": "कोई पूर्वानुमान उपलब्ध नहीं",
    "Day": "दिन",
    "Temp": "तापमान",
    "Rain": "वर्षा",
    "Wind": "हवा",
    "Pest risk and weather trends for": "के लिए कीट जोखिम और मौसम के रुझान",
    "Current Risk Factors": "वर्तमान जोखिम कारक"
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  return useContext(LanguageContext);
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('preferredLang') || 'English';
  });

  useEffect(() => {
    localStorage.setItem('preferredLang', language);
  }, [language]);

  const t = (key) => {
    if (translations[language] && translations[language][key]) {
      return translations[language][key];
    }
    return translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
